<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KontenFormulirSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('konten_formulir')->insert([

            // ================= LOWONGAN 1 =================
            [
                'idLowongan' => 1,
                'namaField' => 'Nama Lengkap',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'NRP',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Nomor mahasiswa',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'Email',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Email aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'Fakultas',
                'tipeField' => 'select',
                'opsi_field' => 'Farmasi,Hukum,Bisnis & Ekonomika,Teknik,Psiokologi,Industri Kreatif',
                'help_text' => 'Pilih fakultas',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'Jenis Kelamin',
                'tipeField' => 'radio',
                'opsi_field' => 'Laki-Laki,Perempuan',
                'help_text' => 'Pilih jenis kelamin',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'Alasan Melamar',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Jelaskan alasan melamar',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'Pengalaman Organisasi',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Opsional',
                'required' => 0,
                'status' => 1,
            ],
            [
                'idLowongan' => 1,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV terbaru',
                'required' => 1,
                'status' => 1,
            ],

            // ================= LOWONGAN 2 =================
            [
                'idLowongan' => 2,
                'namaField' => 'Nama Lengkap',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 2,
                'namaField' => 'Email',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Email aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 2,
                'namaField' => 'Minat Bisnis',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Bidang minat',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 2,
                'namaField' => 'Skill',
                'tipeField' => 'checkbox',
                'opsi_field' => 'Marketing,Design,Finance,IT,Research',
                'help_text' => 'Pilih skill',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 2,
                'namaField' => 'IPK',
                'tipeField' => 'number',
                'opsi_field' => null,
                'help_text' => 'Contoh 3.50',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 2,
                'namaField' => 'Alasan Melamar',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Jelaskan alasan',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 2,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV',
                'required' => 1,
                'status' => 1,
            ],

            // ================= LOWONGAN 3 =================
            [
                'idLowongan' => 3,
                'namaField' => 'Nama',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 3,
                'namaField' => 'Email',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Email aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 3,
                'namaField' => 'IPK',
                'tipeField' => 'number',
                'opsi_field' => null,
                'help_text' => 'Minimal 3.0',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 3,
                'namaField' => 'Komitmen',
                'tipeField' => 'radio',
                'opsi_field' => 'Rendah,Sedang,Tinggi',
                'help_text' => 'Tingkat komitmen',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 3,
                'namaField' => 'Pengalaman',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Organisasi/seminar',
                'required' => 0,
                'status' => 1,
            ],
            [
                'idLowongan' => 3,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV',
                'required' => 1,
                'status' => 1,
            ],

            // ================= LOWONGAN 4 =================
            [
                'idLowongan' => 4,
                'namaField' => 'Nama',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 4,
                'namaField' => 'Email',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Email aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 4,
                'namaField' => 'MS Office',
                'tipeField' => 'radio',
                'opsi_field' => 'Dasar,Menengah,Mahir',
                'help_text' => 'Skill Office',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 4,
                'namaField' => 'Administrasi',
                'tipeField' => 'radio',
                'opsi_field' => 'Baik,Sangat Baik,Excellent',
                'help_text' => 'Kemampuan admin',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 4,
                'namaField' => 'Pengalaman Kerja',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Opsional',
                'required' => 0,
                'status' => 1,
            ],
            [
                'idLowongan' => 4,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV',
                'required' => 1,
                'status' => 1,
            ],

            // ================= LOWONGAN 5 =================
            [
                'idLowongan' => 5,
                'namaField' => 'Nama Lengkap',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 5,
                'namaField' => 'Email',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Email aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 5,
                'namaField' => 'No HP',
                'tipeField' => 'phone',
                'opsi_field' => null,
                'help_text' => 'Nomor aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 5,
                'namaField' => 'Komunikasi',
                'tipeField' => 'radio',
                'opsi_field' => 'Baik,Sangat Baik,Excellent',
                'help_text' => 'Skill komunikasi',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 5,
                'namaField' => 'Pengalaman',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Pengalaman layanan',
                'required' => 0,
                'status' => 1,
            ],
            [
                'idLowongan' => 5,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV',
                'required' => 1,
                'status' => 1,
            ],

            // ================= LOWONGAN 6 =================
            [
                'idLowongan' => 6,
                'namaField' => 'Nama',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 6,
                'namaField' => 'NIM',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Nomor mahasiswa',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 6,
                'namaField' => 'Pengalaman Event',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Pengalaman event',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 6,
                'namaField' => 'Motivasi',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Alasan melamar',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 6,
                'namaField' => 'Skill',
                'tipeField' => 'checkbox',
                'opsi_field' => 'Organisasi,Leadership,Komunikasi',
                'help_text' => 'Pilih skill',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 6,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV',
                'required' => 1,
                'status' => 1,
            ],

            // ================= LOWONGAN 7 =================
            [
                'idLowongan' => 7,
                'namaField' => 'Nama Lengkap',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Sesuai KTM',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 7,
                'namaField' => 'Email',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Email aktif',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 7,
                'namaField' => 'Motivasi',
                'tipeField' => 'textarea',
                'opsi_field' => null,
                'help_text' => 'Alasan melamar',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 7,
                'namaField' => 'Pengalaman Startup',
                'tipeField' => 'text',
                'opsi_field' => null,
                'help_text' => 'Pengalaman startup',
                'required' => 0,
                'status' => 1,
            ],
            [
                'idLowongan' => 7,
                'namaField' => 'Skill',
                'tipeField' => 'checkbox',
                'opsi_field' => 'Marketing,Design,IT,Business,Research',
                'help_text' => 'Pilih skill',
                'required' => 1,
                'status' => 1,
            ],
            [
                'idLowongan' => 7,
                'namaField' => 'CV',
                'tipeField' => 'file',
                'opsi_field' => null,
                'help_text' => 'Upload CV',
                'required' => 1,
                'status' => 1,
            ],

        ]);
    }
}
